### ISSUE TITLE
Using the 'real' module should be configurable

### ISSUE THREAD

**Issue by MaryBartlett** [plasticine/inject-loader#12]
This pull request resulted in the 'real' module being loaded if it wasn't mocked out https://github.com/plasticine/inject-loader/pull/7

Ideally this should be configurable - and present a warning that the module isn't being mocked out. 

There should also be some documentation around this as it's not clear the changes on upgrading from 1.0.0 to 2.0.1.

**Comment by djskinner** [comment]
+1. Is call-thru to the original dependency supported at all currently? I'm migrating from proxyquire and would like to make use of this to reduce the amount of work I need to do.

**Comment by plasticine** [comment]
Hey there. 👋  Bit overdue, but trying to get back to these.

I’m not sure I understand — currently if a replacement is not passed to the created module inject function then the original is used. This is the current behaviour, but could certainly use better docs (the whole module could!).

If I’m missing something then please feel free to clarify and re-open.
