### ISSUE TITLE
Not working with babel 6

### ISSUE THREAD

**Issue by ondrejsevcik** [plasticine/inject-loader#13]
Hi, I've just upgraded from Babel 5.3.3 to Babel 6.9.0 and a lot of my tests stopped working.
I'm using latest jasmine (2.4) with karma test runner and webpack as a preprocessor.

```
// my package.json setup
"babel-core": "6.9.0",
"babel-loader": "6.2.4",
"babel-preset-es2015": "6.9.0",
"babel-preset-react": "6.5.0",
"babel-preset-stage-0": "6.5.0",
"babel-plugin-transform-decorators-legacy": "1.3.4",
"inject-loader": "2.0.1",
```

Do you have any idea where is the problem? My guess is it's because inject-loader was written for Babel 5 but wasn't upgraded for babel 6 yet. Is that right?

**Comment by aaronjensen** [comment]
@ondrejsevcik you'll probably need https://github.com/59naga/babel-plugin-add-module-exports 

We need this to get `inject-loader` working properly, unfortunately.

**Comment by ondrejsevcik** [comment]
Awesome! it works as expected. 

Thank you
