### ISSUE TITLE
Loader didn't return a function error [3.0.0-beta1]

### ISSUE THREAD

**Issue by Aaronius** [plasticine/inject-loader#18]
When I try to upgrade from 2.x to 3.0.0-beta1 I start getting the following errors:

```
ERROR in Loader /Users/aahardy/dev/extension-support-testrunner/node_modules/inject-loader/lib/index.js didn't return a function
 @ ./src/lib/actions/__tests__/setCustomerIds.test.js 4:29-64

ERROR in Loader /Users/aahardy/dev/extension-support-testrunner/node_modules/inject-loader/lib/index.js didn't return a function
 @ ./src/lib/sharedModules/__tests__/mcidInstance.test.js 4:32-65
```

I'm guessing it has to do with the es6 modules in 3.x or something.

**Comment by plasticine** [comment]
@aaronius thanks will have a look 👍🏼

**Comment by oviava** [comment]
```js
function inject(source) {
  this.cacheable && this.cacheable();
  return 'module.exports = ' + createInjectorFunction(this, source);
}

// Object.defineProperty(exports, "__esModule", {
//   value: true
// });
// exports.default = inject;

module.exports = inject;
`

a bit of hit & miss as I don't understand webpack loader system that well but this fixed it for me

**Comment by lvthanh101** [comment]
hi @plasticine, do you have plan to fix this bug?

**Comment by plasticine** [comment]
@lvthanh101 Yep, just haven’t had time. Hopefully soon.

**Comment by zincli** [comment]
hey man, I guess you made a mistake on return value. like @oviava said

```
function inject(source) {
  this.cacheable && this.cacheable();
  return 'module.exports = ' + createInjectorFunction(this, source);
}
```

the return value should be a module, it should export some thing. so `module.exports` here should not omit.

#19 got everything broken.

**Comment by zincli** [comment]
https://github.com/plasticine/inject-loader/blob/master/lib/index.js#L107  here's the problem

**Comment by plasticine** [comment]
Please check out `3.0.0-beta3` which should fix this issue and also introduces support for webpack2.
