### ISSUE TITLE
Not working with AMD modules

### ISSUE THREAD

**Issue by samny** [plasticine/inject-loader#21]
I can't get this to work when loading AMD modules, but works fine for CommonJS and ES6 modules. Is this a known issue?

**Comment by plasticine** [comment]
@samny I’ve not built any support for AMD modules at this point no. If it’s something that is of interest it’s possible I could add it in a future version. Would love a PR! <3

**Comment by sterling** [comment]
I'm running into issues with amd modules as well. Would love to see support in the future!
