### ISSUE TITLE
Cannot find module 'inject!../../server'

### ISSUE THREAD

**Issue by lewis-elliott** [plasticine/inject-loader#30]
After running `npm install inject-loader --save-dev` I get this when I try use the loader through require:

`const inject = require('inject!../../server')`

Is there anything else that needs to be configured?

Webpack 1.13 and babel 6.2.4

```
loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /(node_modules|server)/,
        query: {
          cacheDirectory: true,
          presets: ["es2015", "react", "stage-0"]
        }
      },
```

**Comment by sjalgeo** [comment]
@lewis-elliott did you resolve this? if so what was the issue?
