### ISSUE TITLE
not compatible with create-react-app

### ISSUE THREAD

**Issue by thg303** [plasticine/inject-loader#39]
` Do not use import syntax to configure webpack loaders.`
shows this error message with create-react-app version 1.3.0 and fails the test

**Comment by vladimir-tikhonov** [comment]
Sounds like [this eslint rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-webpack-loader-syntax.md). Could you try to disable in in `eslint` config?

**Comment by plasticine** [comment]
Pretty sure @vladimir-tikhonov is correct, @thg303 are you able to provide any more information here?

**Comment by thg303** [comment]
react-create-app is a zero-config boilerplate. so unless you do an `eject` you may not access to webpack config files.

**Comment by plasticine** [comment]
@thg303 Hey there — yep I’m aware of create react app. The offending eslint rule is [this one](https://github.com/facebookincubator/create-react-app/blob/master/packages/eslint-config-react-app/index.js#L209).

If the warning is just coming from your test code you should just add an `// eslint-disable-import/no-webpack-loader-syntax` or similar.
