### ISSUE TITLE
Any chance of transitive dependencies ?

### ISSUE THREAD

**Issue by DrGor** [plasticine/inject-loader#44]
Thanks for this nice library.
Is there any chance of adding support for injecting transitive dependencies ?

Module A ----imports ---->  Module B  ----imports ----> Module C
I want to be able to mock Module C when testing Module A.

**Comment by morfj** [comment]
Strictly speaking, you are not testing ModuleA in that case, you are testing ModuleA & ModuleB collaboration.

**Comment by plasticine** [comment]
@DrGor Yep, @morfj is correct. Implementing this is not really something that I’m interested in supporting, as I feel it’s a pretty unusual use-case. Feel free to re-open or submit a PR if you don’t agree though.
