### ISSUE TITLE
Webpack 3 compatibility

### ISSUE THREAD

**Issue by MaxMilton** [plasticine/inject-loader#46]
I saw this commit which adds basic Webpack 3 compatibility — https://github.com/plasticine/inject-loader/commit/313f7964bbfcd0f40e769efa0235984d82977145#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 — however, this change hasn't been released to NPM. Is there anything that's preventing this from being released?

This package is the last piece of the puzzle before we can update https://github.com/vuejs-templates/webpack for Webpack 3 compatibility; ref: https://github.com/vuejs-templates/webpack/issues/751

**Comment by plasticine** [comment]
`3.0.1` published.

**Comment by MaxMilton** [comment]
Thank you very much!
