### ISSUE TITLE
define dependencies not to wrap globally

### ISSUE THREAD

**Issue by stephanos** [plasticine/inject-loader#5]
I often use lodash. When I have a file with 5 dependencies where I want to mock everything but lodash I currently need to specify all other 4 dependencies explicitly: `inject?lib1&lib2&lib3&lib4!testable`. Therefore it would be great if the plugin could have some kind of global configuration to always exclude libraries like lodash.

**Comment by plasticine** [comment]
Yeah, that would be neat—thanks for the suggestion.

**Comment by thomasklein** [comment]
+1

**Comment by plasticine** [comment]
This is resolved by #7.

All dependencies of a module are still injected by default, however if a replacement is no provided it will roll back to the original dependency.
