### ISSUE TITLE
Not working with React Native packager?

### ISSUE THREAD

**Issue by jarecsni** [plasticine/inject-loader#51]
Tried the simplest of cases, something like

const injector = require('inject-loader!./SomeModule')

Got the below exception 

 Cannot find module 'inject-loader!./ExerciseExternalView' from 'ExerciseExternalView.spec.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)

Not sure if inject-loader is supposed to work with RN?

**Comment by plasticine** [comment]
@jarecsni This is expected — React Native does not use Webpack, instead bundles code with https://github.com/facebook/metro

`inject-loader` only works with Webpack.
