### ISSUE TITLE
npm publish?

### ISSUE THREAD

**Issue by jerrysu** [plasticine/inject-loader#9]
We're starting to use this on a project and noticed that the last merge which hasn't been published to npm does what we'd like `inject-loader` to do. We are considering forking `inject-loader` so that we can get more tests written, but would be easier to just keep pushing this project forward.

**Comment by plasticine** [comment]
Hey there, @jerrysu glad to hear you’re looking to use `inject-loader` :)

I was hanging back from publishing a new version as the changes are breaking so it would be a major version bump, and I have some other enhancements that I’m working on. That said, version numbers are cheap, so I’ll publish `2.0.0` today. :)

**Comment by plasticine** [comment]
@jerrysu `2.0.0` is published

**Comment by jerrysu** [comment]
Thanks @plasticine!

**Comment by plasticine** [comment]
@jerrysu Welcome! Let me know if you have any feedback if you end up using it in anger. :metal:
